import type { Metadata } from "next";
import "./globals.css";
import StoreProvider from "@/app/StoreProvider";
import { Web3ModalProvider } from "@/context/Web3ModalProvider";
import QueryProvider from "@/lib/providers/QueryProvider";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Staking | KHAN's Project",
  description: "Generated by create next app",
  icons: {
    icon: { rel: "ico", url: "/favicon.ico", type: "image/ico" },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Script src='https://telegram.org/js/telegram-web-app.js' strategy='beforeInteractive' />
      <body className='scdream8-font'>
        <QueryProvider>
          <Web3ModalProvider>
            <StoreProvider>{children}</StoreProvider>
          </Web3ModalProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
